name: Matrix Demo 
on: push
jobs: 
  build: 
    continue-on-error: true   #Continue on error on job level tell github action to continue executing jobs that are related to this matrix even if some jobs for some combinations failed
    strategy: 
      matrix:   # When using matrix if one job fails, the other jobs are canceled and skipped
        node-version: [12, 14, 16]    
        operating-system: [ubuntu-latest, windows-latest]
        include:    # Add single combination with the include key
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:    # Use include and exclude to add or remove some combination
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}   # Run multiple jobs in parallel with different os
    steps:
      - name: Get Code 
        uses: actions/checkout@v3 
      - name: Install NodeJS
        uses: actions/setup-node@v3 
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci 
      - name: Build project
        run: npm rum build 