name: Reuseable Deploy 
on: 
  workflow_call:
    inputs: 
      artifact-name:
        description: The name of the deployable artifact files 
        required: false  # false mean this workflow can be called without providing a value
        default: dist 
        type: string
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code 
        uses: actions/download-artifact@v3 
        with: 
          name: ${{ inputs.artifact-name }} 
      - name: List files 
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."